version: "3.6"
services:
  # App services
  lofi-stack:
    image: lofi-stack:latest
    build:
      context: .
      target: runner
    environment:
      PORT: 3000
      NODE_ENV: "production"
      APP_ENV: "DEVELOPMENT"
      DB_URL: "http://host.docker.internal:8080"
      DB_AUTH_TOKEN: ""
    expose:
      - 3000
      - 8080
    ports:
      - "3000:3000"
      - "8080:8080"
